### ISSUE TITLE
SQL Error with ubuntu example

### ISSUE THREAD

**Issue by GabrieleCicconetti** [JetBrains/teamcity-docker-samples#11]
I'm using TeamCity version 2023.05.4 this is the docker-compose

```
version: '3.3'
services:
  db:
    networks:
      - my_net
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  teamcity:
    networks:
      - my_net
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent-1:
    networks:
      - my_net
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
  teamcity-agent-2:
    networks:
      - my_net
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
networks:
  my_net:
    ipam:
      config:
        - subnet: 172.16.0.0/16
```

This is the error i get when i try to visit the teamcity web page

`Unexpected exception: SQL error when doing 'Querying for a single value '
ERROR: unrecognized configuration parameter "lc_collate" while performing SQL query: SQL UNKNOWN: show lc_collate: org.postgresql.util.PSQLException: ERROR: unrecognized configuration parameter "lc_collate"`

Is this some error with the postgres version?

Thank you :)
