### ISSUE TITLE
Couldn't find Agent

### ISSUE THREAD

**Issue by xts-velkumars** [JetBrains/teamcity-docker-samples#4]
@All, 

I couldn't find any Agents, after ran my docker compose file. 

My Agent is running fine, inside my container 

![image](https://user-images.githubusercontent.com/13570225/116439840-9b93fa00-a86d-11eb-8140-94e1c568d707.png)

![image](https://user-images.githubusercontent.com/13570225/116440071-bb2b2280-a86d-11eb-9bf8-9da42c720158.png)

Please advise me.

**Comment by wesalexander** [comment]
@xts-velkumars Just ran into this myself - it may be necessary to edit the buildAgent.properties file for each agent to indicate the IP of your host as that file by default points to http:\://localhost\:8111 which will have the agent looking at itself on port 8111. Additionally you may need to update the port to 8112 as that is where compose is mapping the TC server

**Comment by xts-velkumars** [comment]
@wesalexander Thank you for your response. 

I have made couple of changes. 

1. I have changed my sever URL as 8112 in my client buildAgent.properties
2. Inside my docker compose i have changed SERVER_URL as well 

Still no luck, please see the attached screenshot. 

I have attached docker-compose.yml & buildAgent.properties files as well 

[docker-compose.yml.txt](https://github.com/JetBrains/teamcity-docker-samples/files/6396916/docker-compose.yml.txt)
[buildAgent.properties.txt](https://github.com/JetBrains/teamcity-docker-samples/files/6396914/buildAgent.properties.txt)

![image](https://user-images.githubusercontent.com/13570225/116515620-27e40280-a8ea-11eb-967e-640de73c9904.png)

![image](https://user-images.githubusercontent.com/13570225/116515632-2dd9e380-a8ea-11eb-8bed-bedfbc40aa3d.png)

**Comment by xts-velkumars** [comment]
Attaching my folder setup

[TeamCity.zip](https://github.com/JetBrains/teamcity-docker-samples/files/6398191/TeamCity.zip)

**Comment by xts-velkumars** [comment]
@espuuks still no luck. 

I'm battling to configure my Agents. 

I'm getting below messages in my logs

![image](https://user-images.githubusercontent.com/13570225/116650000-eca30b80-a99d-11eb-8fdb-6bcf009a56fc.png)


**My docker-compose**

```
version: '3.1'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./log_dir - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    container_name: "teamcity-server"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
    depends_on:
      - db
  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf    
    environment:
      - AGENT_NAME="Agent"
      - SERVER_URL=http://teamcity:8111
      - DOCKER_IN_DOCKER=start  
  db:
    image: postgres:latest
    container_name: "teamcity-database"
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
```

**buildAgent.properties**

```
name=Agent
ownPort=9090
serverUrl=http\://localhost\:8112

workDir=../work
tempDir=../temp
systemDir=../system

teamcity.docker.use.sudo=true
```
**NOTE:- I have tried with both (8111, 8112) PORTS inside my buildAgent.propeties**
