### ISSUE TITLE
Update multi-node compose sample as "running-builds-node" env var is not supported anymore

### ISSUE THREAD

**Issue by bschaatsbergen** [JetBrains/teamcity-docker-samples#5]
The teamcity servers in the multi node compose sample are making use of an environment variable that's not supported anymore: 
`-Dteamcity.server.role=running-builds-node`

For the sake I've removed the env var in the below compose, this can be replaced with the existing multi node compose sample. I've also removed the `${TEAMCITY_VERSION}` ref as pulling the latest version is more reliable as this repo saves updating the repo, will have to get rid of .env file. 

```
version: '3.1'

# ./buildserver_pgdata - Postgres DB data
# ./data - TeamCity data directory
# ./teamcity-server-logs1 - logs of primary TeamCity server
# ./teamcity-server-logs2 - logs of secondary TeamCity server (running-builds node)
# ./teamcity-server-logs3 - logs of read-only TeamCity server (secondary node)
# ./teamcity-agent-conf1 - conf directory for the build agent
# ./teamcity-agent-conf2 - conf directory for the build agent
# ./teamcity-agent-conf3 - conf directory for the build agent

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: buildserver
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data

  main:
    image: jetbrains/teamcity-server
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./teamcity-server-logs1:/opt/teamcity/logs
    ports:
      - 8111:8111

  node1:
    image: jetbrains/teamcity-server
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./teamcity-server-logs2:/opt/teamcity/logs
    ports:
      - 8112:8111
    environment:
      TEAMCITY_SERVER_OPTS: -Dteamcity.server.rootURL=http://node1:8111
    
  node2:
    image: jetbrains/teamcity-server
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./teamcity-server-logs3:/opt/teamcity/logs
    ports:
    - 8113:8111
    environment:
      TEAMCITY_SERVER_OPTS: -Dteamcity.server.rootURL=http://node2:8111
  
  agent1:
    image: jetbrains/teamcity-agent:latest
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - ./teamcity-agent-conf1:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

  agent2:
    image: jetbrains/teamcity-agent:latest
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - ./teamcity-agent-conf2:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

  agent3:
    image: jetbrains/teamcity-agent:latest
    environment:
        SERVER_URL: http://teamcity:8111
    volumes:
        - ./teamcity-agent-conf3:/data/teamcity_agent/conf
        - /var/run/docker.sock:/var/run/docker.sock
```
